catalogs:
  build:
    '@nuxt/devtools': ^2.5.0
    '@nuxt/eslint': ^1.4.1
    '@nuxt/kit': ^3.17.5
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.1
    '@unocss/eslint-config': ^66.3.2
    '@unocss/nuxt': ^66.3.2
    '@vite-pwa/nuxt': ^1.0.4
    '@vueuse/nuxt': ^13.4.0
    nuxt: ^3.17.5
    unocss: ^66.3.2
    unplugin: ^2.3.5
    vite: ^6.3.5
  dev:
    '@antfu/eslint-config': ^4.16.1
    eslint: ^9.30.0
    eslint-plugin-format: ^1.0.1
    typescript: ^5.8.3
    vue-tsc: ^2.2.10
  frontend:
    '@vueuse/core': ^13.4.0
    pinia: ^3.0.3
    vue: ^3.5.17
  icons:
    '@iconify-json/carbon': ^1.2.10
    '@iconify-json/twemoji': ^1.2.2
  server:
    chokidar: ^4.0.3
    discord.js: ^14.21.0
    nuxt-discord: ^0.0.13

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver

peerDependencyRules:
  ignoreMissing:
    - webpack
